<?php

/**
 * @file
 * Module used to track and manage user defined lists of pids.
 */

/**
 * Implements hook_menu().
 */
function islandora_creative_commons_menu() {
  $items = array();
  $items['admin/islandora/creative-commons'] = array(
    'title' => 'Creative Commons',
    'description' => 'Config DSID and Xpath that creative commons should be added to.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_creative_commons_admin_form'),
    'access arguments' => array('administer'),
    'file' => 'includes/admin.form.inc',
  );
  return $items;
}

/**
 * Alter the image upload forms, to allow a flag to be set for OCR.
 */
function islandora_creative_commons_form_alter(&$form, &$form_state, $form_id) {
  $forms_to_modify = array(
    'xml_form_builder_ingest_form',
    'xml_form_builder_edit_datastream_form',
  );
  if (in_array($form_id, $forms_to_modify)) {
    module_load_include('inc', 'islandora_creative_commons', 'includes/creative_commons');
    islandora_creative_commons_form($form, $form_state);
  }
}